### ISSUE TITLE
How to change batch_size from 4 to other number?

### ISSUE THREAD

**Issue by ghost** [mosturm/SynCellFactory#1]
How to change batch_size from 4 to other number?

**Comment by mosturm** [comment]
Hi Istan,

You can change the batch size for training and validation in the DataLoaders. They are located in SynCellFactory/ControlNet/cldm/cldm.py, starting from line 449. The batch size variable is called bs.

Cheers,
Mo

**Comment by ghost** [comment]
Thank you very much for your guidance!
